sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - .travis/publish.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
  - secure: "pmNax9rwqJlxVYSKSykAMe2jjhdIi8TMnXumkGEEW3TK7SQ3qoThgx1GiItkDf62NhlUJfv6/kfk7UzuVzFNCfDyE3MdZtJyT4IN+jSvuzvc8lYOwsEaaA+s+9bDjeUsHJNkj3RjprBaWwLxxaXaaoXD4wuQ0UDWNd99SNZWXP/vOMmapuEGgSV4tK8eHn+NxMXuwGKjK/6+GDOurJM/wRgaCFO2dWXgXZQp39pdX7kRrcQ6uHUJDOK0aUJDSWdxlQo850BITkFFWCfzYnOn9KZP7tcsM7M60ZiyXO8n344HiHpZ8xCSvI49RppA2wXDcpOdAmAVGAYy143RPQMdkaQMtlduRmv7WVx4z1QqOTKK6n2fUbxwV8j049O1YZVKuHm8CovMjhT0YB14qLwG92vvTX4UIuyr5BlRGbb4/esfxEb+plXBIIM20kNhjjx9d/HgIMpBMhsLWIiFo4l7VXwvKyP7CnDPfrwPj2EM1UUTkRl9csccw/Lcx6LGyNpVmUHd9qsenGs7cScYHe9pYOLNEXooLyvPGpyuxmdQxRi6vbOXx4B7TksDBwHOWa0bAdpnFn6ZD9YeO7/37OVsCLztZFKoWD9OQAy8gfj0r6nDYQzfiepdZvLjncyFM2mjQFF7otyjDNyiY1cl80kYTinvWVdTmEdLtbOTKFTdqJ0="
  # Ex. travis encrypt -r org/repo SONATYPE_USER=your_sonatype_account
  - secure: "aYrXGPXmlGjwgc5nORpIhgTX2XapvgET9SJjtnxcR+UIxTgAkbkuWSluGytIoXtyv2XfaOz5adsPjE84a/o3kJaxTndccM5fQEqTeO4Ajjp5yan9kQMGdg72HE9jOBpSRMejjCewJQXJ7JmzoB+fI4XLUzVsNH5CUHW5J8WX+1huDEyfuRkRwZYxYZkVJcpAAPFVXGBVT/ObLxYp6ZUDE0UbjGCbW+tfzB2CRO0nJ557wwJ3OHK/vTPfzDZeuT0sZM7eDuLhhcUt3ODuoXxS8278zsqzJ8P48XPpwxJGzH2qsOsUDhnhMHjn9g5sJ5SvOxwTh5HrtIAFxsaaRm8eeZlNh8/EbXZPIRqMF0OSN0wyYAAajnt098Cppacqcuco8c6jbivE3ut32mOR468U3OfT5HbIcb/90HrWGUnVwsNjgf7eBkklHuU6hfXEWmDltTK1XylOb/MqIEX+0igsVfwlHntACO4vCzGkgXxW7WA6uhRyl6wEv0IQgRo7ZrO2+uI8WPof2+4So0PITn2z4w11BEiqF8W52Wt+0poVvywwmsozbr3iRdJpR3bIWsDlyuSKory2mfLPoD68MTvWIpePNz0RfOM0nOs0hTRmgQtO2bT05mP24h70HeZdW8At+C+m1bKTJ/mrodlNFyomHqgumKkpoaaU1htEfB0vKLg="
  # Ex. travis encrypt -r org/repo SONATYPE_PASSWORD=your_sonatype_password
  - secure: "VmoyywoEV8jo+fpXMPqj8Xb0cnsDhOtO387Xvl5aNyD6c/LgQg2F8ay8DuW8WrrPMdRRbU5auc4qLqUTfIwkGFLIZYtODD0bK8boOvrogqCF5P2rUiHIcs3aiyZzvi2Md73eZ1m4CFXvNbAzP/oJ8hYHJSyqe6tjIGX5Ioei2b2a5Ti5pZCchHdXHU+nG7M7ZmJWAUV+35ilGS2Kxlwj4KbrLHdTLB2gpFN7ORNU6lBKmWvr6Qp6vSf1RoOpR424nSDHqpWjJW5FYEGm6Wu4rDRI5lfmjmNJ0o/YXr/bpKr7YKDYBOok1Jp+neiBgbyGkbIVelcXf0B6G+BVQw5BqtlO7KxdYhIEltmsIZ5fj5sD6Y7DOEj3C7iZrzQCwnocfqtwNvSkPt+SvCnIj3U1WXK9geqSTmNTuPvW92Z1THZu2T1YZM7ddYO2XAUToTHNA7/9MliqGNyP1w2AKf5FmTauFVU1u7yqIEicifEQHUo0xwpNWAMDFGvSxAlDh8wJ+oXx068hOrQuw8HRioin9um/UjtmoMpIci5ug1SCn/jDLJ0FDC8r/ncnGjMpGEkI5Hoe5QUfp+/hcUJSojiD4qHE00GRVziGoD3iq5hOplTfLwNX3uPu8z57L/ic5zU/gALSpzoedifBS6FZnwZRa5/IGl596YCu6bM6XgDDdf8="
  # Ex. travis encrypt -r org/repo BINTRAY_USER=your_github_account
  - secure: "bAljhUfqAA0xEhVBxTgRfmEXFg+g4+4E+58ewiwMZ/ILoE6qvWwgtBMav2VgYZXiyMJ2UVAVnw+ZlYLb2udxkB8ZfR3Bttdr1hy9lRaOXs01yunOOTNZP1LqXfyzGpa6g1XePJ06FOsSOUa6Y4680O9TclHCq5drl1jfe5obbhcyqadYjbRoP0kKegIUzI0plgCqtTIu+fHeLYeky9EA920VGGHW9fPIpRLeVUu8SfBHYZzeV65q3gjCp8AXBSHsjyFRisLp7QuiBksHJh2dpu8Y7SsSpL+latbw5nzKUFwei15qtqQ7D1rkyAenJxNjQq7z0qBo67C3DAj+Q9TfyYXN+oF4hI6AEeXQxMCjh0Qnhw/ZZsrbyR2dNM/wrNiflgs6Vkr4WtfootzIHUFurVpOguaeIBuFyC3+oXXMAvF7KS/RUcYjR6wd87Grb7F5M0lB+72aDeI8Xe9p6oyxLrDTHJjXuG/+tPKpnJUYJ8taPuw23S9Mk/MuUF9a4UfvFW4Cp2lgb6j1C1B2RsDluf0kOXTBzN7yzvnQcP4nNwPm2o4yp1Wdx2AEw0xOqUvs2BN5QAjb6vzSsKrUe0MtMibgwOyQu+G6//Z4vJ3P2fDCpbMiLURMFLXEV9d9TyX0/7wO/bLWZuEqaWbeIYZHKU9kEGKSWmZBAFA5OxguxvM="
  # Ex. travis encrypt -r org/repo BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx
  - secure: "RFfni5wlzBr99O4L1dj+rmywvmYs9iam1k68mBQGZIY67Exbag9gsIMfg6WySKC7f6eP0RBl8f4ORTwDH89qlErOHzHfM7zdvbqehMBiFUooON9h3Q9GAfVf/dGuNZriyRg7/LW7+l2GhgkaHkYCc4fMeQWXy6XA+tf+C1L5VsNwDzDr0g+AOJodUcp/uehCypd9MaRB5Cd5xQlTnpzZ6mTrKhNWAPTeWJRYFvb1gte1Cu2nLDrnV+QOgSaaVAxU7sj2+f98gg7sJJb5sMD1Prf0ICpdbNx4WlZRhZsfskJqYnlaGnYu6E9VntxQHZHG3eMU0yxrcgXu/zaJNh3BGQevXfSwR+QY4OUWjQH5NMXYGCYN+UgYahZNogj/hWJtiRi6UTosR5kzTXgg/WhflsF2DORgRRXAMz2q+87zjVdZQkS111SpN3l+rY7mU0KnqjGmpB81Io7GxU82crC0oaZ0MZyPsGWz50p46KyIFX846As+Mg8Cfl9N5N4yj2Kpl3vXU1T1Q7QQPxiXiaXFOfhBr7yKJ8LSdTSNTlr7Fd0Ke63fbMeS/DOwFTZlID3qNshxGcsF6gBJUpRjgIRf3HZ1He4msfR4bwCur36Tqi3L3YM4FZouY2y08vZXuuHE2HBcamqnEqnuqV9SfgoDBgvguyp591eWfjqDf+HuEAQ="
